-- DML-HR-실습.SQL

-- 1. 모든 직원의 FIRST_NAME, LAST_NAME, EMAIL, HIRE_DATE를 조회
SELECT FIRST_NAME, LAST_NAME, EMAIL, HIRE_DATE FROM EMPLOYEES;

-- 2. 모든 직원의 풀네임(FIRST_NAME+공백문자+LAST_NAME)을 조회
SELECT FIRST_NAME||' '||LAST_NAME FULLNAME FROM EMPLOYEES;

-- 3. 모든 직원의 JOB_ID의 종류를 조회
SELECT DISTINCT JOB_ID FROM EMPLOYEES;

-- 4. 월급이 10000미만인 직원을 조회
SELECT * FROM EMPLOYEES WHERE SALARY < 10000;

-- 5. 월급이 10000에서 20000사이인 직원을 조회 (10000,20000 포함)
SELECT * FROM EMPLOYEES WHERE SALARY BETWEEN 10000 AND 20000;

-- 6. 월급이 2000 배수인 직원을 조회
SELECT * FROM EMPLOYEES WHERE MOD(SALARY, 2000) = 0; 

-- 7. 월급이 10000이거나 15000이거나 20000인 직원을 조회
SELECT * FROM EMPLOYEES WHERE SALARY IN(10000,15000,20000);

-- 8. 월급이 15000이상인 직원의 수를 조회
SELECT COUNT(*) FROM EMPLOYEES WHERE SALARY >= 15000;

-- 9. 커미션퍼센트가 정해지지 않은 직원의 수를 조회
SELECT COUNT(*) FROM EMPLOYEES WHERE COMMISSION_PCT IS NULL;

-- 10. 커미션퍼센트 곱하기 월급이 가장 많은 순으로 조회 (커미션퍼센트가 NULL인 경우 제외)
SELECT SALARY, COMMISSION_PCT, COMMISSION_PCT*SALARY FROM EMPLOYEES 
WHERE COMMISSION_PCT IS NOT NULL ORDER BY COMMISSION_PCT*SALARY DESC;

-- 11. 50번 부서의 직원들을 월급이 높은 순으로 조회
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID=50 ORDER BY SALARY DESC;

-- 12. 매니저아이디가 114인 직원들을 입사일 최근 순으로 조회
SELECT * FROM EMPLOYEES WHERE MANAGER_ID = 114 ORDER BY HIRE_DATE DESC;

-- 13. 직원들의 직원아이디와 연봉을 높은 순으로 조회 (연봉은 월급*12로 계산)
SELECT EMPLOYEE_ID, SALARY, SALARY*12 "연봉" FROM EMPLOYEES ORDER BY SALARY*12 DESC;

-- 14. FIRST_NAME에 'P'문자가 들어간 직원을 조회
SELECT FIRST_NAME FROM EMPLOYEES WHERE FIRST_NAME LIKE '%P%';

-- 15. FIRST_NAME이나 LAST_NAME에 'K'문자가 들어간 직원을 조회
SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE FIRST_NAME LIKE '%K%' OR LAST_NAME LIKE '%K%';

-- 16. FIRST_NAME이 'L'이나 'E'로 시작하는 직원을 조회
SELECT FIRST_NAME FROM EMPLOYEES WHERE FIRST_NAME LIKE 'L%' OR FIRST_NAME LIKE 'E%';

-- 17. 입사일에 대해서 내림차순, 월급에 대해서 내림차순 정렬해서 직원을 조회
SELECT * FROM EMPLOYEES ORDER BY HIRE_DATE DESC, SALARY DESC;

-- 18. 커미션퍼센트가 NULL이 아닌 직원들의 월급*커미션퍼센트를 내림차순으로 풀네임과 함께 조회
SELECT FIRST_NAME||' '||LAST_NAME 풀네임, SALARY*COMMISSION_PCT FROM EMPLOYEES 
WHERE COMMISSION_PCT IS NOT NULL ORDER BY SALARY*COMMISSION_PCT DESC;

-- 19. 부서아이디 내림차순 정렬, 잡아이디로 오름차순 정렬, 월급으로 내림차순 정렬하여 조회
SELECT DEPARTMENT_ID, JOB_ID, SALARY FROM EMPLOYEES ORDER BY DEPARTMENT_ID DESC, JOB_ID, SALARY DESC;

-- 20. 부서아이디로 오름차순 정렬, 직원들의 풀네임을 오름차순 정렬, 월급을 내림차순 정렬하여 조회
--     단, 부서아이디가 30번 이상, 월급인 8000 이상인 경우에 한함
SELECT DEPARTMENT_ID, FIRST_NAME||' '||LAST_NAME FULLNAME, SALARY FROM EMPLOYEES 
WHERE DEPARTMENT_ID >= 30 AND SALARY >=8000 
ORDER BY DEPARTMENT_ID, FIRST_NAME||' '||LAST_NAME, SALARY DESC; 






