--실습 2. 이니셜 계정의 STUDENT 테이블
--          1) 한 행의 데이터를 입력하는 프로시져 PROC_INSERT_STUDENT 생성
--          2) STNO를 입력하면 이름을 반환하는 함수 FUNC_GET_STNAME 생성
--          3) 프로시져와 함수 호출하여 결과 출력

CREATE OR REPLACE PROCEDURE PROC_INSERT_STUDENT(
	P_STDNAME IN OUT VARCHAR2,
	P_STDMAIL IN OUT VARCHAR2,
	P_STDTEL IN OUT VARCHAR2
)
IS 
BEGIN 
	INSERT INTO STUDENT VALUES(STD_SEQ.NEXTVAL, P_STDNAME, P_STDMAIL, P_STDTEL);
END;

CREATE OR REPLACE FUNCTION FUNC_GET_STNAME(P_STNO NUMBER)
RETURN VARCHAR2
IS 
	V_STDNAME VARCHAR2(20);
BEGIN 
	SELECT STD_NAME INTO V_STDNAME
	FROM STUDENT
	WHERE STD_NUMBER = P_STNO;
 	RETURN V_STDNAME;
END;

SELECT * FROM STUDENT;









