SELECT * FROM EMPLOYEES;

SELECT * FROM DEPARTMENTS;

SELECT COUNT(*) FROM DEPARTMENTS; 

SELECT 1+2 FROM dual;
SELECT 'hello' FROM dual;
SELECT 'HELLO' FROM dual;

SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES;

SELECT DEPARTMENT_ID, DEPARTMENT_NAME FROM DEPARTMENTS;

SELECT FIRST_NAME, LAST_NAME, SALARY, CITY FROM EMP_DETAILS_VIEW;