-- VIEW 연습

-- 1) 직원아이디, 직원풀네임, 부서아이디, 부서명, 월급 조회하는 VW_EMPDEPT 뷰를 생성
CREATE OR REPLACE VIEW VW_EMPDEPT AS 
SELECT E.EMPLOYEE_ID, E.FIRST_NAME||' '||E.LAST_NAME "직원풀네임", D.DEPARTMENT_ID, D.DEPARTMENT_NAME, E.SALARY
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT * FROM VW_EMPDEPT;

-- 2) 직원아이디, 직원풀네임, 부서아이디, 부서명, LOCATION_ID, CITY 조회하는 VW_EMPLOCATION 뷰를 생성
CREATE OR REPLACE VIEW VW_EMPLOCATION AS
SELECT E.EMPLOYEE_ID, E.FIRST_NAME||' '||E.LAST_NAME "직원풀네임", D.DEPARTMENT_ID, L.LOCATION_ID, L.CITY 
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID 
	AND D.LOCATION_ID = L.LOCATION_ID;

SELECT * FROM VW_EMPLOCATION;



