CREATE SEQUENCE SEQ_SMOKE;

CREATE TABLE SMOKE(
	SID NUMBER PRIMARY KEY,
	ORGNAME NVARCHAR2(200) NOT NULL,
	ORGTEL VARCHAR2(20) NOT NULL,
	ORGYEAR NUMBER NOT NULL,
	DATADATE CHAR(10) NOT NULL,
	SIGUNGU NVARCHAR2(20) NOT NULL,
	DSCOUNT NUMBER NOT NULL,
	MWCOUNT NUMBER NOT NULL
);

SELECT * FROM SMOKE;
