-- 각 부서의 평균 급여(Average Salary)를 계산하고 급여가 가장 높은 부서도 확인하세요.
SELECT DEPARTMENT_ID, AVG(SALARY) FROM EMPLOYEES 
GROUP BY DEPARTMENT_ID ORDER BY AVG(SALARY) DESC;



SELECT
	FIRST_NAME AS "G-NAME",
	DEPARTMENT_ID AS "G-ID",
	MAX(SALARY),
	MIN(SALARY), 
	ROUND(AVG(SALARY), 2) AS "평균급여",
	GROUPING(DEPARTMENT_ID) AS "그룹=0"
FROM
	EMPLOYEES
GROUP BY
	ROLLUP(FIRST_NAME, DEPARTMENT_ID)
ORDER BY FIRST_NAME;

