-- EXCEPTION(예외)
-- PL/SQL 수행 중에 발생 가능한 오류

DECLARE 
	V_NO NUMBER;
BEGIN
	-- DEPARTMENT_NAME은 VARCHAR2, V_NO에 할당 불가
	SELECT DEPARTMENT_NAME INTO V_NO
	FROM DEPARTMENTS
	WHERE DEPARTMENT_ID = 50;
	P('예외가 발생하면 이 구문은 수행 안됨!');
	EXCEPTION
		WHEN VALUE_ERROR THEN P('VALUE ERROR 발생함!');
END;

-- 여러 예외 처리
DECLARE 
	V_NO NUMBER;
BEGIN
	SELECT DEPARTMENT_NAME INTO V_NO
	FROM DEPARTMENTS;
	EXCEPTION
		-- 타입이 맞지 않을때
		WHEN VALUE_ERROR THEN P('VALUE ERROR 발생!');
		-- 변수에 담을 수 있는 행의 수보다 많은 행이 리턴되면
		WHEN TOO_MANY_ROWS THEN P('TOO MANY ROWS 발생!');
		-- 그 외의 모든 예외
		WHEN OTHERS THEN P('그 외 모든 예외 발생!');
END;

-- 예외코드 / 예외메세지
DECLARE 
	V_NO NUMBER;
BEGIN
	SELECT DEPARTMENT_NAME INTO V_NO
	FROM DEPARTMENTS;
	EXCEPTION
		WHEN TOO_MANY_ROWS THEN 
			P(SQLCODE); -- 예외 코드
			P(SQLERRM); -- 예외 메시지
END;
