-- 제약조건 (CONSTRAINTS)
-- 컬럼에 입력되는 데이터를 제한해서
-- 데이터베이스의 무결성을 지킬 목적으로 사용되는 객체

-- NOT NULL : NULL 허용하지 않음
-- UNIQUE : 컬럼의 값이 유일해야 함
-- PRIMARY KEY : NOT NULL + UNIQUE
-- CHECK : 조건에 맞는 데이터만 허용
-- FORGEIGN KEY : 다른 테이블의 PK값만 허용

CREATE TABLE PERSON (
	PNO NUMBER PRIMARY KEY,
	PNAME VARCHAR2(200) NOT NULL,
	PAGE NUMBER CHECK (PAGE>0),
	PHOBBY VARCHAR2(50) CHECK (PHOBBY IN('축구', '야구')),
	PMP CHAR(13) UNIQUE
);

-- PNAME은 NOT NULL제약
-- INSERT INTO PERSON VALUES(1, NULL, 10, '축구', '010-0000-0000');

INSERT INTO PERSON VALUES(1, '홍길동', 10, '축구', '010-0000-0000');

-- PAGE는 CHECK (PAGE>0)제약
--INSERT INTO PERSON VALUES(1, '강감찬', -10, '축구', '010-0000-0000');
INSERT INTO PERSON VALUES(2, '강감찬', 20, '축구', '010-1234-5678');

-- PHOBBYSMS CHECK (PHOBBY IN('축구', '야구'))
--INSERT INTO PERSON VALUES(3, '이순신', 50, '농구', '010-1234-1234');
INSERT INTO PERSON VALUES(3, '이순신', 50, '야구', '010-0123-1234');

SELECT * FROM PERSON;

-- 테이블레벨 제약
CREATE TABLE PERSON2(
	PNO NUMBER,
	PNAME VARCHAR2(200) NOT NULL, -- NOT NULL은 컬럼레벨로 부여
	PAGE NUMBER,
	PHOBBY VARCHAR2(50),
	PMP CHAR(13),
	CONSTRAINT PK_PERSON2_PNO PRIMARY KEY(PNO),
	CONSTRAINT CK_PERSON2_PAGE CHECK (PAGE>0),
	CONSTRAINT CK_PERSON2_PHOBBY CHECK (PHOBBY IN('축구', '야구')),
	CONSTRAINT UQ_PERSON2_PMP UNIQUE (PMP)
);






