-- 종합실습-cky.sql

-- [종합실습]

-- 1. 데이터 요구사항
-- 학생들의 성적관리
-- 학생엔터티, 과목엔터티, 성적엔터티
-- 학생속성 : 학생번호, 학생명, 이메일, 휴대폰번호
-- 과목속성 : 과목번호, 과목명
-- 성적속성 : 학생번호, 과목번호, 점수

-- 2. 논리/물리 모델 설계 (ERWin)
-- score.erwin

-- 3. 구현 요구사항
-- 1) 3개의 테이블 생성
-- 2) 2개의 시퀀스 생성
CREATE TABLE STUDENT(
	STD_NUMBER NUMBER PRIMARY KEY,
	STD_NAME VARCHAR2(20) NOT NULL,
	STD_MAIL VARCHAR2(100),
	STD_TEL VARCHAR2(20)
);
CREATE SEQUENCE STD_SEQ;

CREATE TABLE SUBJECT(
	SUB_NUMBER NUMBER PRIMARY KEY,
	SUB_NAME VARCHAR2(20)
);
CREATE SEQUENCE SUB_SEQ;

CREATE TABLE GRADE(
	STD_NUMBER NUMBER,
	SUB_NUMBER NUMBER,
	SCORE NUMBER(4,1) CHECK (SCORE>0),
	FOREIGN KEY(STD_NUMBER) REFERENCES STUDENT(STD_NUMBER),
	FOREIGN KEY(SUB_NUMBER) REFERENCES SUBJECT(SUB_NUMBER)
);

-- 3) 데이터 입력
--     학생 3명(홍길동,강감찬,이순신) 생성, 과목 3개(국어,영어,수학) 생성,
--     학생/과목별 성적 생성
INSERT INTO STUDENT VALUES(STD_SEQ.NEXTVAL, '홍길동', 'hong@emil.com', '010-1234-1234');
INSERT INTO STUDENT VALUES(STD_SEQ.NEXTVAL, '강감찬', 'kang@emil.com', '010-5678-5678');
INSERT INTO STUDENT VALUES(STD_SEQ.NEXTVAL, '이순신', 'lee@emil.com', '010-1234-5678');
INSERT INTO SUBJECT VALUES(SUB_SEQ.NEXTVAL, '국어');
INSERT INTO SUBJECT VALUES(SUB_SEQ.NEXTVAL, '영어');
INSERT INTO SUBJECT VALUES(SUB_SEQ.NEXTVAL, '수학');

INSERT INTO GRADE VALUES(1,1,100);
INSERT INTO GRADE VALUES(1,2,90);
INSERT INTO GRADE VALUES(1,3,80);
INSERT INTO GRADE VALUES(2,1,90);
INSERT INTO GRADE VALUES(2,2,80);
INSERT INTO GRADE VALUES(2,3,70);
INSERT INTO GRADE VALUES(3,1,80);
INSERT INTO GRADE VALUES(3,2,70);
INSERT INTO GRADE VALUES(3,3,60);

COMMIT;
SELECT * FROM STUDENT;
SELECT * FROM SUBJECT;
SELECT * FROM GRADE;

-- 4) 뷰 생성(VW_SCORE) : 학생번호, 학생명, 과목명, 국어, 영어, 수학 
CREATE OR REPLACE VIEW VW_SCORE AS
SELECT ST.STD_NUMBER, ST.STD_NAME, SB.SUB_NAME, G.SCORE
FROM STUDENT ST, SUBJECT SB, GRADE G
WHERE ST.STD_NUMBER = G.STD_NUMBER 
	AND SB.SUB_NUMBER = G.SUB_NUMBER
ORDER BY SB.SUB_NUMBER, ST.STD_NUMBER;
SELECT * FROM VW_SCORE;

-- 5) SCORE/SCORE 사용자 생성
CREATE USER SCORE IDENTIFIED BY SCORE;
GRANT CONNECT, RESOURCE TO SCORE;

-- 6) SCORE 사용자에게 VW_SCORE 조회 권한 부여
GRANT SELECT ON KSK.VW_SCORE TO SCORE;


