-- 집합
-- 집합연산을 하려면 조회되는 컬럼의 수와 타입이 일치해야 함
-- UNION : 합집합
-- UNION ALL : 합집합 + 교집합
-- INTERSECT : 교집합
-- MINUS : 차집합

CREATE TABLE T1(
	SNAME VARCHAR2(20),
	SAGE NUMBER
);

CREATE TABLE T2(
	SNAME VARCHAR2(20),
	SAGE NUMBER
);

TRUNCATE TABLE T1;

INSERT INTO T1 VALUES('페이커', 20);
INSERT INTO T1 VALUES('케리아', 10);
INSERT INTO T1 VALUES('구마유시', 30);
INSERT INTO T2 VALUES('페이커', 20);
INSERT INTO T2 VALUES('홍길동', 10);
INSERT INTO T2 VALUES('강감찬', 30);

COMMIT;

SELECT * FROM T1;
SELECT * FROM T2;

-- 합집합 (UNION)
SELECT * FROM T1 UNION SELECT * FROM T2;

-- 합교집합 (UNION ALL)
SELECT * FROM T1 UNION ALL SELECT * FROM T2;

-- 교집합 (INTERSECT)
SELECT * FROM T1 INTERSECT SELECT * FROM T2;

-- 차집합 (MINUS)
SELECT * FROM T1 MINUS SELECT * FROM T2;
SELECT * FROM T2 MINUS SELECT * FROM T1;

