-- 커서 실습

--  1. JOBS테이블의 모든 행을 조회할 수 있는 커서를 만들고 모든 행의 정보를 출력
DECLARE
	CURSOR CUR_JOBS IS
		SELECT * FROM JOBS;
BEGIN
	FOR V_CUR_JOBS IN CUR_JOBS
	LOOP
		P('ID:'||V_CUR_JOBS.JOB_ID);
		P(' 직업명:'||V_CUR_JOBS.JOB_TITLE);
		P(' 최소월급:'||V_CUR_JOBS.MIN_SALARY);
		P(' 최대월급:'||V_CUR_JOBS.MAX_SALARY||CHR(10));
	END LOOP;
END;

-- 2. 부서아이디가 50 이하인 모든 행을 조회할 수 있는 커서를 만들고 모든 행의 정보를 출력
DECLARE
	CURSOR CUR_DEPT IS
	SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_ID <= 50;
BEGIN
	FOR V_CUR_DEPT IN CUR_DEPT
	LOOP
		P('D/ID:'||V_CUR_DEPT.DEPARTMENT_ID
		||' 부서명:'||V_CUR_DEPT.DEPARTMENT_NAME
		||' M/ID:'||V_CUR_DEPT.MANAGER_ID
		||' L/ID:'||V_CUR_DEPT.LOCATION_ID||CHR(10));
	END LOOP;
END;

-- 3. 월급이 전체 직원의 평균월급보다 적은 직원의 아이디와 풀네임을 조회할 수 있는
--    커서를 만들어 출력
DECLARE
	CURSOR CUR_EMP IS 
	SELECT EMPLOYEE_ID, FIRST_NAME||' '||LAST_NAME FULLNAME
	FROM EMPLOYEES
	WHERE SALARY <(SELECT AVG(NVL(SALARY,0)) 
			FROM EMPLOYEES);
BEGIN
	FOR V_CUR_EMP IN CUR_EMP
	LOOP
		P('ID:'||V_CUR_EMP.EMPLOYEE_ID||' 풀네임:'||V_CUR_EMP.FULLNAME||CHR(10));
	END LOOP;
END;

-- 4. RESION_ID를 입력하면 소속 국가들의 모든 정보를 조회할 수 있는 커서를 만들어 출력
DECLARE
	CURSOR CUR_COUNTRIES(P_REGION_ID COUNTRIES.REGION_ID%TYPE) 
	IS
	SELECT * FROM COUNTRIES
	WHERE REGION_ID = P_REGION_ID;
BEGIN
	FOR V_CUR_C IN CUR_COUNTRIES(2)
	LOOP
		P('C/ID:'||V_CUR_C.COUNTRY_ID
		||' 국가명:'||V_CUR_C.COUNTRY_NAME
		||' R/ID:'||V_CUR_C.REGION_ID||CHR(10));
	END LOOP;
END;

-- 5. 직원아이디(100~206)를 입력하면 직원과 같은 부서에 근무하는 직원의 직원아이디, 풀네임, 월급을
--    조회할 수 있는 커서를 만들어 출력
DECLARE
	CURSOR CUR_EMP(P_CUR_EMP EMPLOYEES.EMPLOYEE_ID%TYPE)
	IS
	SELECT EMPLOYEE_ID, FIRST_NAME||' '||LAST_NAME FULLNAME, SALARY
	FROM EMPLOYEES
	WHERE DEPARTMENT_ID = (
		SELECT DEPARTMENT_ID FROM EMPLOYEES
		WHERE EMPLOYEE_ID = P_CUR_EMP);
BEGIN
	FOR V_CUR_EMP IN CUR_EMP(206)
	LOOP
		P('ID:'||V_CUR_EMP.EMPLOYEE_ID||' 이름:'||V_CUR_EMP.FULLNAME||
		' 월급:'||V_CUR_EMP.SALARY||CHR(10));
	END LOOP;
END;


